server:
  port: 8080

spring:
  application:
    name: ai-mock-interview

  datasource:
    url: jdbc:postgresql://localhost:5432/interviewdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

